// ── Join Code helpers — Phase 2 Gate 4 ────────────────────────────────────────
// Top-level /joinCodes/{code} collection.
// 6-char alphanumeric, reusable until regenerated by coach.

import { db as firestoreDb } from '../firebase';
import { doc, getDoc, setDoc, query, collection, where, getDocs, updateDoc } from 'firebase/firestore';

const CHARS = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no 0/O/1/I ambiguity

const genCode = () =>
  Array.from({ length: 6 }, () => CHARS[Math.floor(Math.random() * CHARS.length)]).join('');

// Create (or replace) the active join code for a team.
// Deactivates any previous code for this team first.
export const createJoinCode = async ({ orgId, teamId, teamName, orgName, createdByUid }) => {
  // Deactivate old codes for this team
  try {
    const q = query(
      collection(firestoreDb, 'joinCodes'),
      where('orgId', '==', orgId),
      where('teamId', '==', teamId),
      where('active', '==', true)
    );
    const snap = await getDocs(q);
    await Promise.all(snap.docs.map(d => updateDoc(d.ref, { active: false })));
  } catch { /* best-effort */ }

  const code = genCode();
  await setDoc(doc(firestoreDb, `joinCodes/${code}`), {
    code,
    orgId,
    teamId,
    teamName: teamName || '',
    orgName: orgName || '',
    createdByUid,
    createdAt: new Date().toISOString(),
    active: true,
  });
  return code;
};

// Fetch the current active join code for a team (for display in Manage).
export const getActiveJoinCode = async (orgId, teamId) => {
  try {
    const q = query(
      collection(firestoreDb, 'joinCodes'),
      where('orgId', '==', orgId),
      where('teamId', '==', teamId),
      where('active', '==', true)
    );
    const snap = await getDocs(q);
    if (snap.empty) return null;
    return snap.docs[0].data();
  } catch {
    return null;
  }
};

// Look up a code entered by a user. Returns the code doc or null.
export const lookupJoinCode = async (code) => {
  try {
    const snap = await getDoc(doc(firestoreDb, `joinCodes/${code.trim().toUpperCase()}`));
    if (!snap.exists()) return null;
    const data = snap.data();
    if (!data.active) return null;
    return data;
  } catch {
    return null;
  }
};

// Redeem a join code — writes parent role + member doc.
// Called after Google sign-in is confirmed.
export const redeemJoinCode = async (code, uid, userProfile) => {
  const codeData = await lookupJoinCode(code);
  if (!codeData) throw new Error('Invalid or expired join code.');

  const now = new Date().toISOString();
  const roleData = {
    role: 'parent',
    teamId: codeData.teamId,
    grantedByUid: codeData.createdByUid,
    grantedAt: now,
    status: 'active',
    removedAt: null,
    removedBy: null,
  };

  // Write role doc
  await setDoc(doc(firestoreDb, `users/${uid}/roles/${codeData.orgId}`), roleData);

  // Write denormalized member doc
  await setDoc(doc(firestoreDb, `orgs/${codeData.orgId}/members/${uid}`), {
    uid,
    displayName: userProfile?.displayName || '',
    email: userProfile?.email || '',
    photoURL: userProfile?.photoURL || null,
    ...roleData,
  });

  return codeData; // returns { orgId, teamId, teamName, orgName }
};
